# Generated by Django 4.2.30 on 2026-05-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0003_complaint_escalation_count_complaint_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hearing_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('meeting_type', models.CharField(choices=[('video', 'Video Conference'), ('audio', 'Audio Call'), ('chat', 'Text Chat')], default='video', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_hearings', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='complaints.complaint')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_hearings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
