# Generated by Django 4.2.30 on 2026-05-01 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('service_type', models.CharField(max_length=50)),
                ('office_location', models.CharField(max_length=200)),
                ('incident_date', models.DateTimeField()),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('evidence_documents', models.JSONField(default=list)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_investigation', 'Under Investigation'), ('verified', 'Verified - Action Taken'), ('rejected', 'Rejected - Insufficient Evidence'), ('escalated', 'Escalated to Higher Authority'), ('resolved', 'Resolved - Action Completed'), ('dismissed', 'Dismissed - False Report')], default='pending', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('investigation_notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('feedback_to_citizen', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
