# Generated by Django 4.2.30 on 2026-04-30 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('birth_certificate', 'Birth Certificate'), ('tax_id', 'Tax ID')], max_length=50)),
                ('applicant_name_bn', models.CharField(max_length=200)),
                ('applicant_name_en', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('document_verification', 'Document Verification'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delayed', 'Delayed')], default='submitted', max_length=50)),
                ('current_officer', models.CharField(max_length=100)),
                ('office_location', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_completion_date', models.DateTimeField()),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(null=True, upload_to='qr_codes/')),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='BriberyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=50, unique=True)),
                ('service_type', models.CharField(max_length=50)),
                ('office_location', models.CharField(max_length=200)),
                ('incident_date', models.DateTimeField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('evidence_documents', models.JSONField(default=list)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='applications.application')),
            ],
        ),
    ]
