# Generated by Django 4.2.30 on 2026-05-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_trust_score'),
    ]

    operations = [
    ]
