# Generated by Django 4.2.30 on 2026-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20260503_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_level',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
